title: Portfolio
author: Matthew MacDonald
 
theme: minima

markdown: kramdown

description: Projects and Demos
show_downloads: false

header_pages:
 - compute.md
 - graphics.md
 - compiler.md
 - about.md

